FROM python:alpine

WORKDIR /app/
COPY web/requirements.txt /app/requirements.txt
RUN apk add --update --no-cache build-base linux-headers python3-dev && \
    pip --no-cache-dir install -r requirements.txt && \
    apk del build-base linux-headers python3-dev

ENV PYTHONPATH=/app/

COPY web /app/
EXPOSE 8000

CMD ["uwsgi", "--ini", "/app/uwsgi/uwsgi.ini"]

