version: "3.6"
services:
    longpoll:
        image: nsychev/abit-bot
        build: .
        depends_on:
            - db
        command: "./longpoll.py"
        restart: always
    updater:
        image: nsychev/abit-bot
        build: .
        volumes:
            - ./static/:/static/
        depends_on:
            - db
        command: "./loop.py"
        restart: always
    db:
        image: mongo:4
        restart: always

