version: "3.6"
services:
    longpoll:
        image: nsychev/abit-bot
        build:
            context: .
            dockerfile: Dockerfile.bot
        depends_on:
            - db
        command: "./longpoll.py"
        restart: always
    updater:
        image: nsychev/abit-bot
        build:
            context: .
            dockerfile: Dockerfile.bot
        depends_on:
            - db
        command: "./loop.py"
        restart: always
    web:
        image: nsychev/abit-web
        build:
            context: .
            dockerfile: Dockerfile.web
        depends_on:
            - db
        restart: always
    db:
        image: mongo:4
        restart: always

